
import React from 'react';
import { 
  House, 
  Broadcast, 
  Users, 
  PlusSquare, 
  MagnifyingGlass, 
  Play, 
  Pause, 
  Info, 
  CaretLeft, 
  CaretRight, 
  Bell, 
  SpeakerHigh, 
  ArrowsOut, 
  VideoCamera, 
  Waveform, 
  X, 
  Heart,
  Lock,
  LockOpen,
  CreditCard,
  ShieldCheck,
  ChartBar,
  ChartLineUp,
  Globe,
  Gear
} from '@phosphor-icons/react';

export const Icons = {
  Home: House,
  Live: Broadcast,
  Artists: Users,
  MyList: PlusSquare,
  // Fix: Adding PlusSquare mapping as it is used directly in pages/Player.tsx for the shop action
  PlusSquare: PlusSquare,
  Search: MagnifyingGlass,
  Play: Play,
  Pause: Pause,
  Info: Info,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  Bell: Bell,
  VolumeHigh: SpeakerHigh,
  ArrowsOut: ArrowsOut,
  Camera: VideoCamera,
  Waveform: Waveform,
  X: X,
  Heart: Heart,
  Lock: Lock,
  LockOpen: LockOpen,
  CreditCard: CreditCard,
  Shield: ShieldCheck,
  Chart: ChartBar,
  Analytics: ChartLineUp,
  Globe: Globe,
  Settings: Gear,
};
